[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.17"
optimizer = true
optimizer-runs = 1
fs_permissions = [{ access = "read", path = "." }]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "${RPC_MAIN}"
goerli = "${RPC_GOERLI}"
